### ISSUE TITLE
Transfer / Comment

### ISSUE THREAD

**Issue by qzio** [dulvie/emmy#165]
503 error when creating (POST) a comment on a `Transfer`.

The comment is created properly in the database.

The error seems to be in the redirect in the `CommentsController`

**Comment by maxhansson** [comment]
I can't recreate the error

**Comment by qzio** [comment]
Possiblr fixed by the kunna merge. I was attenpting this in the old version

**Comment by qzio** [comment]
Closing this. Lets create new issue if we see this again
