### ISSUE TITLE
Batch: should have link to Article type - show page

### ISSUE THREAD

**Issue by qzio** [dulvie/emmy#171]
On the Batch show page, there should be a link to the parent article type for easy navigation.

**Comment by maxhansson** [comment]
Should it be a tab like quantities that show parent info (article form)

**Comment by qzio** [comment]
Hm.... I don't think so, it would be enought to be able to navigate to the connected "Item" -page.

**Comment by maxhansson** [comment]
Is it something like the customer link in create sale?

**Comment by qzio** [comment]
No, on the sale page there is a link to "Create a customer".

On the Batch *SHOW* page, that is, when there is already a created batch, I'm viewing an existing batch, I would like to be able to easily navigate to the connected Item.
