### ISSUE TITLE
Wizard for a new production (roast) state information needed.

### ISSUE THREAD

**Issue by qzio** [dulvie/emmy#175]
When creating a new roast, some information is needed to be known by the user.

Including but not limited to
- Raw material: from which item type?
- Raw material: from which batch? does the batch contain enough raw material:
- end batch? is this created using the production forms? created manually?
- end item (artikel) ? does it exist?
- how are price handled? copied from "item" (artikel) ? user doesn't know how the system works...
- ..?

This should be stated early on since a "refinement', "roast", or "production" can not be completed without the information.

**Comment by maxhansson** [comment]
Would it be something similar to the field info help but that covers the entire operation

**Comment by qzio** [comment]
yes/no.

When you attempt to create a new "Production" only a few fields is visible. but when you move the "Production" -state forward, more fields becomes visible, and you need to fill in more info.

Some kind  of "?" or "i" or similar would help the user so that he/she knows what info will be required to actually complete all the states of a roast.

**Comment by maxhansson** [comment]
Under the menu help we have some examples on wizards. Is this a alternative.

**Comment by qzio** [comment]
Yes, lets try that.

**Comment by maxhansson** [comment]
Should we move this documentation from the wizard to doc.emmy app?

**Comment by qzio** [comment]
Yes, I think so. 👍

**Comment by maxhansson** [comment]
first try of documentation for production

**Comment by maxhansson** [comment]
Can we close and remove the branch production_wizard? Documentetion moved to docs.emmy-app.

**Comment by qzio** [comment]
Yes, good idea
