### ISSUE TITLE
Translation missing: se.purchase_items (<title> on `purchases/3/purchase_items/new`)

### ISSUE THREAD

**Issue by qzio** [dulvie/emmy#177]

**Comment by qzio** [comment]
Is there a PR for this?

**Comment by maxhansson** [comment]
The only translation I found were two date-field witch I fixed in the commit. But is the error-discription pointing at something else?

**Comment by qzio** [comment]
Yes, There is a translation error in the `<title>` tag on the purchases/:purchase_id/purchase_items/new page.
