### ISSUE TITLE
Profile/Logout menu needs styling.

### ISSUE THREAD

**Issue by qzio** [dulvie/emmy#188]
The pop-down menu for the profile/logout menu in the top left corner is lacking style.
Regression because of the new layout.

**Comment by maxhansson** [comment]
How it would be to place the profile menu as the first line in the main menu.

**Comment by maxhansson** [comment]
Is the profil-menu ok?

**Comment by qzio** [comment]
I think I prefer to have the profile menu outside of the app navigation.

The profile menu is for the user's account. It is a separate thing than the application itself.

I think most of the web apps out there have this distinction between "application navigation" and "profile settings"

**Comment by maxhansson** [comment]
Ok
