### ISSUE TITLE
Enable "Comments" on a sale, printed on the PDF invoice

### ISSUE THREAD

**Issue by qzio** [dulvie/emmy#262]
It should be possible to add a comment on a sale.
The comment should be printed on the PDF-invoice.
This to enable extra information to the end-customer.

**Comment by maxhansson** [comment]
I agree. But comments should be both external (printed on the invoice) and partly for internal information.

**Comment by qzio** [comment]
yes, two different kind's of "comments"

**Comment by maxhansson** [comment]
Worth noting
- The comment's location on the invoice
- Only the first comment is posted on the invoice
- the returnpath after adding a comment is edit_

**Comment by qzio** [comment]
Yes I agree.

Two types of comments, one that is displayed on the pdf invoice, but it should also be possible to add comments to a sale for "internal" notes.

**Comment by maxhansson** [comment]
merged #291
