### ISSUE TITLE
"Payment term" must be more flexible.

### ISSUE THREAD

**Issue by qzio** [dulvie/emmy#263]
When creating a sale, the "Payment Term" is set.

Today it is a fixed value of either "30" or "10".

This must be more flexible.
Remember to add proper validation, it must always be a single number!

**Comment by maxhansson** [comment]
Some options:
1) Having a default value such as 30 that can be changed
2) Have an underlying table where different values can be registered 
The value is important for monitoring of payments.

**Comment by qzio** [comment]
I think it would be overkill to have a separate database table for this, as it is a single value.

For now, I would say that we implement this as a "text" field in the UI, and continue with the INTEGER in the database.

However, the user input must be validated that it's a number, and that it's between 1-365
