### ISSUE TITLE
Show price with VAT included in invoice

### ISSUE THREAD

**Issue by svenbox** [dulvie/emmy#265]
An option to show the price per line with tax instead of without. 
For our organisation showing the total tax is enough, price per item/line with tax included would be better than without.

**Comment by qzio** [comment]
This might actually be true for most organizations, maybe we should just switch for everybody.

**Comment by maxhansson** [comment]
I agree. We replace the amount with VAT included.

**Comment by qzio** [comment]
closed by e084dc7
