### ISSUE TITLE
Template for invoice emails

### ISSUE THREAD

**Issue by svenbox** [dulvie/emmy#271]
Editable template for the email sent out with the PDF invoice

**Comment by maxhansson** [comment]
An ide for templates:
A model with: name, language code, text, organization_id and perhaps template_type.
When sending email the confirmdialoge is changed. The user have option to choose text from created templates. Then view for email take the text from the model. 

Some questions: 

1. How are ordinary texts attach invoice distinguishable from reminders?
2. Should a button (send reminder) bee availible when due date passed and the payment is not reported.?

An email function may be useful in other contexts. Some example. 
- As a reminder-function
- Dispatch of additional offer
- Pushing for repeat sales

**Comment by svenbox** [comment]
"Send invoice with email template X" is simple enough with a dropdown? 
So the user can pick from default template or "reminder" template for example. 
As a start limit this function to two templates-  "invoice template" and "invoice reminder template".

**Comment by maxhansson** [comment]
Some points that are not obvious
1: Placement in the menu system under General.
2: Default values for the mail_templates form.

**Comment by maxhansson** [comment]
A few points
1) Changed layout for sales list. Button instead of link with envelope_icon.
2) What to do if mail_template is missing?

**Comment by maxhansson** [comment]
Sending invoice and reminder, se #272

**Comment by maxhansson** [comment]
Functionality:
1) Under General / E-mail templates, the subject and text for e-mail are registered
2) If no templates are registered then default values are used.
3) When Sale is approved, the possibility of sending the invoice by e-mail is opens
4) You can choose between the texts registered with the type of "invoice"
5) When an email is sent, the option closes. Duplication is prevented.
6) When due date has been passed and no payment is registered, the possibility of sending a reminder opens
7) You can choose between the texts registered with the type "reminder"
8) The ability to send reminders closes when payment is registered.

Reflection:
1) Should the reminder date be saved? Allows you to see the latest reminder date when posting a reminder.

**Comment by maxhansson** [comment]
Can this issue be closed? Se pull request #303

**Comment by qzio** [comment]
yes
